[build]
  base    = "/"
  publish = "/dist"
  command = "yarn build"

[context.production]
  command = "yarn build"
  [context.production.environment]
    REACT_APP_SERVER_URL = "https://wfhu-frontend-prod.studiotenfour.biz"
    REACT_APP_API_URL = "https://wfhu-backend-prod.studiotenfour.biz"

[context.deploy-preview.environment]
  command = "yarn build"
  REACT_APP_API_URL = "https://wfhu-backend-staging.studiotenfour.biz"

[context.branch-deploy]
  command = "yarn build"
  [context.staging.environment]
    REACT_APP_SERVER_URL = "https://wfhu-frontend-staging.studiotenfour.biz"
    REACT_APP_API_URL = "https://wfhu-backend-prod.studiotenfour.biz"

