[build]
  publish = "dist/"
  base = "/"
  command = "yarn build"

[context.production]
  publish = "dist/"
  command = "yarn build"
  [context.production.environment]
    REACT_APP_SERVER_URL = "https://www.wfhuniv.com"
    REACT_APP_API_URL = "https://api.wfhuniv.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://wfhu-backend-staging.studiotenfour.biz"

[context.branch-deploy]
  publish = "dist/"
  command = "yarn build"
  [context.branch-deploy.environment]
    REACT_APP_API_URL = "https://wfhu-backend-staging.studiotenfour.biz"
    NODE_VERSION = "14.15.4"
    NPM_VERSION = "6.14.10"
